{% set name = "restview" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2b989610aaed2fd42da64f6cdc539cf3ee70ce370bcba872db72421ad515dd1e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - restview = restview.restviewhttp:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - docutils
    - pygments
    - python >=3.6
    - readme_renderer

test:
  imports:
    - restview
  commands:
    - restview -h

about:
  home: https://mg.pov.lt/restview/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: ReStructuredText viewer
  description: |
    A viewer for ReStructuredText documents that renders them on the fly. Pass
    the name of a ReStructuredText document to restview, and it will launch a
    web server on localhost:random-port and open a web browser. Every time you
    reload the page, restview will reload the document from disk and render it.
    This is very convenient for previewing a document while you’re editing it.
  dev_url: https://github.com/mgedmin/restview

extra:
  recipe-maintainers:
    - moorepants
